[application]
name = "oxvault"
default_platform = "desktop"
asset_dir = "assets"

[desktop]
title = "Oxidized Vault"
width = 900
height = 600

[bundle]
identifier = "com.agucova.oxcrypt.desktop"

# Disable automatic web builds
[web]
enabled = false
