[application]
name = "oxvault"
default_platform = "desktop"

[desktop]
title = "Oxidized Vault"
width = 900
height = 600

[application.asset_dir]
path = "assets"

# Disable automatic web builds
[web]
enabled = false
